#enable-magisk-update = true
parallel-jobs = 2
build-mode = "apk"   

# ReVanced"

# ReVanced Extended by anddea
[YouTube-anddea]
app-name = "YouTube RVX Anddea"
archive-dlurl = "https://archive.org/download/com.google.android.youtube-20.25.37-1555295680-min-api-26arm-64-v-8aarmeabi-v-7a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
github-releases-dlurl = "https://github.com/SharathGames1/APKs/releases/latest"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
cli-version = "v1.4.0"
cli-source = "MorpheApp/morphe-cli"
build-mode = "apk"
version = "20.25.37"
rv-brand = "RVX"
included-patches = "'Hide Shorts dimming' 'MaterialYou'"
patcher-args = "-e 'Custom branding name for YouTube' -OappName='YouTube RVX anddea' -e 'Settings for YouTube' -OrvxSettingsLabel=ReVanced Extended -e 'Theme' -OdarkThemeBackgroundColor=#ff000000 --continue-on-error"# Morphe
[YouTube-Morphe]
app-name = "YouTube Morphe"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "dev"
build-mode = "apk"
rv-brand = "Morphe"
excluded-patches = "'Change header'"
patcher-args = "-e 'Custom branding' -OcustomName='YouTube Morphe'  -e 'Theme' -OdarkThemeBackgroundColor=#000000"
#enabled= "false"

