name: Build Modules
on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true

  workflow_dispatch:
  schedule:
    - cron: 0 0/3 * * *

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "25"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true


      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > sign.keystore
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > ks-p12.keystore

      - name: Update config
        if: ${{ inputs.from_ci }}
        run: |
          if git checkout origin/update build.md; then
            UPDATE_CFG=$(./build.sh config.toml --config-update)
            if [ "$UPDATE_CFG" ]; then
              echo "$UPDATE_CFG" > config.json
            fi
          fi

      - name: Get next version code
        id: next_ver_code
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         TAG=$(gh release list -L 20 | awk -F '\t' '{print $3}' | grep -E '^[0-9]+$' | head -n 1)

         if [ -z "$TAG" ]; then TAG=0; fi

         echo "NEXT_VER_CODE=$((TAG + 10000))" >> $GITHUB_OUTPUT

      - name: Build modules/APKs
        run: if [ -f "config.json" ]; then bash ./build.sh config.json; else bash  ./build.sh config.toml; fi
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
          
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq unzip wget zip

      # ⚡ Install Apktool v3.0.1
      - name: Install Apktool
        run: |
          wget -q https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool
          wget -q https://github.com/iBotPeaches/Apktool/releases/download/v3.0.1/apktool_3.0.1.jar -O apktool.jar
          chmod +x apktool
          sudo mv apktool /usr/local/bin/apktool
          sudo mv apktool.jar /usr/local/bin/apktool.jar

      # 🏗️ Install Android Build Tools r34
      - name: Install Android Build Tools
        run: |
          wget -q https://dl.google.com/android/repository/build-tools_r34-linux.zip -O build-tools.zip
          unzip -q build-tools.zip -d android-build-tools

      # 🔎 Find latest Dolphin build
      - name: Find latest Dolphin build and decompile
        continue-on-error: true
        run: |
          DOLPHIN_APK_URL=$(curl -s https://dolphin-emu.org/download/ \
            | grep -Eo 'https://dl\.dolphin-emu\.org/builds/[a-z0-9/]+/dolphin-master-[0-9]+-[0-9]+\.apk' \
            | awk -F'[-/.]' '{
              v=$(NF-2); b=$(NF-1);
              if (v>V || (v==V && b>B)) {V=v; B=b; U=$0}
            } END{print U}')
          NAME=$(basename "$APK_URL" .apk)
          echo "DOLPHIN_APK_URL=$DOLPHIN_APK_URL" >> $GITHUB_ENV
          echo "DOLPHIN_NAME=$DOLPHIN_NAME" >> $GITHUB_ENV
          curl -L "$DOLPHIN_APK_URL" -o temp/dolphin.apk
          apktool d temp/dolphin.apk -o temp/dolphin-src
      # ✏️ Patch targetSdkVersion
      - name: Patch targetSdkVersion and compile Dolphin
        continue-on-error: true
        run: |
          sed -i -E 's/^( *targetSdkVersion: *)[0-9]+/\129/' temp/dolphin-src/apktool.yml
          apktool b temp/dolphin-src -o temp/dolphin-patched.apk
          java -jar android-build-tools/android-14/lib/apksigner.jar sign \
            --ks ks-p12.keystore \
            --ks-type PKCS12 \
            --ks-key-alias "${{ secrets.KEYSTORE_ALIAS }}" \
            --ks-pass pass:${{ secrets.KEYSTORE_PASS }} \
            --out build/$DOLPHIN_NAME.apk \
            temp/dolphin-patched.apk
      - name: Get latest Eden build and decompile
        continue-on-error: true
        run: |
          EDEN_APK_URL=$(curl -fSsL https://git.eden-emu.dev/api/v1/repos/eden-ci/nightly/releases | jq -r '.[0] | .assets | .[] | select(.name | test("standard.apk"))| .browser_download_url')

          EDEN_NAME=$(basename "$EDEN_APK_URL" .apk)

          echo "EDEN_APK_URL=$EDEN_APK_URL" >> $GITHUB_ENV
          echo "EDEN_NAME=$NAME" >> $GITHUB_ENV
          curl -L "$EDEN_APK_URL" -o temp/eden.apk
          apktool d temp/eden.apk -o temp/eden-src

      - name: Patch AndroidManifest.xml
        continue-on-error: true
        run: |
            sed -i 's/dev\.eden\.eden_emulator\.nightly/com.tencent.ig/g' temp/eden-src/AndroidManifest.xml
            apktool b temp/eden-src -o temp/patched.apk
            java -jar android-build-tools/android-14/lib/apksigner.jar sign \
            --ks ks-p12.keystore \
            --ks-type PKCS12 \
            --ks-key-alias "${{ secrets.KEYSTORE_ALIAS }}" \
            --ks-pass pass:${{ secrets.KEYSTORE_PASS }} \
            --out build/$EDEN_NAME.apk \
            temp/eden-patched.apk
            
         
          
            
      - name: Get output
        id: get_output
        run: |
          DELIM="$(openssl rand -hex 8)"
          echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
          cat build.md >> "$GITHUB_OUTPUT"
          echo "Patched Dolphin SDK 29: ${DOLPHIN_NAME}/nPatched Eden PUBG: ${EDEN_NAME}" >> "$GITHUB_OUTPUT"
          echo "${DELIM}" >> "$GITHUB_OUTPUT"
          cp -f build.md build.tmp
      
      - name: Upload release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
          BODY: ${{ steps.get_output.outputs.BUILD_LOG }}
        run: |
          if gh release view "$TAG" >/dev/null 2>&1; then
            gh release edit "$TAG" --title "Release" --notes "$BODY"
            gh release upload "$TAG" ./build/* --clobber
          else
            gh release create "$TAG" ./build/* --title "Release" --notes "$BODY"
          fi

      - name: Update modules changelog and update json
        id: update_config
        run: |
          git checkout -f update || git switch --discard-changes --orphan update
          cp -f build.tmp build.md
          get_update_json() {
            echo "{
            \"version\": \"$1\",
            \"versionCode\": ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }},
            \"zipUrl\": \"$2\",
            \"changelog\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build.md\"
          }"
          }

          cd build || { echo "build folder not found"; exit 1; }
          for OUTPUT in *module*.zip; do
            [ "$OUTPUT" = "*module*.zip" ] && continue
            ZIP_S=$(unzip -p "$OUTPUT" module.prop)
            if ! UPDATE_JSON=$(echo "$ZIP_S" | grep updateJson); then continue; fi
            UPDATE_JSON="${UPDATE_JSON##*/}"
            VER=$(echo "$ZIP_S" | grep version=)
            VER="${VER##*=}"
            DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
            get_update_json "$VER" "$DLURL" >"../$UPDATE_JSON"
          done
          cd ..

          find . -name "*-update.json" | grep . || : >dummy-update.json

      - name: Commit module json changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
          git add build.md *-update.json
      
          if ! git diff --cached --quiet; then
            git commit -m "Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}"
            git push origin HEAD:update
          else
            echo "no changes!"
          fi

